name: create-release
on: 
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
jobs:
  run-semantic-release:
    runs-on: windows-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.2.0'
      - name: Install dependencies 
        run: npm ci
      - name: Release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release

          cd..
          cd..

          $version = Get-Content ./version.txt
          $changelog = Get-Content ./CHANGELOG.md

          git add .\version.txt
          git add .\CHANGELOG.md
          git commit -m "release ${version} [skip ci]" ./version.txt
          git push

          git tag "v$version"
          
          git push --tags