name: create-release
on: 
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
jobs:
  run-semantic-release:
    runs-on: windows-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.2.0'
      - name: Install dependencies 
        run: |
          npm install semantic-release
          npm install @semantic-release/changelog@5.0.1
          npm install @google/semantic-release-replace-plugin
      - name: Release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # npm exec semantic-release
          npx semantic-release

          ls
          # cd..
          # ls
          # cd..
          # ls


          $version = Get-Content ./version.txt
          $changelog = Get-Content ./CHANGELOG.md

          Write-Host "version : v$version"
          Write-Host "CHANGELOG: $changelog"


          # remove tag created by semantic-release
          
          git push --delete origin "$version"



          git add .\version.txt
          git add .\CHANGELOG.md
          git commit -m "release v${version} [skip ci]"
          git push

          git tag -f "$version"
          
          git push origin $version